language: cpp

git:
  depth: false

env:
  global:
    - BUILD_TOOLCHAIN="Unix Makefiles"

dist: xenial

matrix:
  include:
    - name: "Linux GCC 4.8 [32-bit] [DBG]"
      os: linux
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [valgrind, g++-4.8, g++-4.8-multilib]
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CC=gcc-4.8 && CXX=g++-4.8 && CXXFLAGS=-m32"

    - name: "Linux GCC 4.8 [64-bit] [DBG]"
      os: linux
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [valgrind, g++-4.8, g++-4.8-multilib]
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CC=gcc-4.8 && CXX=g++-4.8 && CXXFLAGS=-m64"

    - name: "Linux GCC 4.9 [32-bit] [DBG]"
      os: linux
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [valgrind, g++-4.9, g++-4.9-multilib]
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CC=gcc-4.9 && CXX=g++-4.9 && CXXFLAGS=-m32"

    - name: "Linux GCC 4.9 [64-bit] [DBG]"
      os: linux
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [valgrind, g++-4.9, g++-4.9-multilib]
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CC=gcc-4.9 && CXX=g++-4.9 && CXXFLAGS=-m64"

    - name: "Linux GCC 5.X [32-bit] [DBG]"
      os: linux
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [valgrind, g++-5, g++-5-multilib]
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CC=gcc-5 && CXX=g++-5 && CXXFLAGS=-m32"

    - name: "Linux GCC 5.X [64-bit] [DBG]"
      os: linux
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [valgrind, g++-5, g++-5-multilib]
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CC=gcc-5 && CXX=g++-5 && CXXFLAGS=-m64"

    - name: "Linux GCC 6.X [32-bit] [DBG]"
      os: linux
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [valgrind, g++-6, g++-6-multilib]
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CC=gcc-6 && CXX=g++-6 && CXXFLAGS=-m32"

    - name: "Linux GCC 6.X [64-bit] [DBG]"
      os: linux
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [valgrind, g++-6, g++-6-multilib]
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CC=gcc-6 && CXX=g++-6 && CXXFLAGS=-m64"

    - name: "Linux GCC 7.X [32-bit] [DBG]"
      os: linux
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [valgrind, g++-7, g++-7-multilib]
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CC=gcc-7 && CXX=g++-7 && CXXFLAGS=-m32"

    - name: "Linux GCC 7.X [64-bit] [DBG]"
      os: linux
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [valgrind, g++-7, g++-7-multilib]
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CC=gcc-7 && CXX=g++-7 && CXXFLAGS=-m64"

    - name: "Linux GCC 8.X [32-bit] [DBG]"
      os: linux
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [valgrind, g++-8, g++-8-multilib]
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CC=gcc-8 && CXX=g++-8 && CXXFLAGS=-m32"

    - name: "Linux GCC 8.X [64-bit] [DBG]"
      os: linux
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [valgrind, g++-8, g++-8-multilib]
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CC=gcc-8 && CXX=g++-8 && CXXFLAGS=-m64"

    - name: "Linux GCC 8.X [32-bit] [REL]"
      os: linux
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [valgrind, g++-8, g++-8-multilib]
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CC=gcc-8 && CXX=g++-8 && CXXFLAGS=-m32"

    - name: "Linux GCC 8.X [64-bit] [REL]"
      os: linux
      addons:
        apt:
          sources: [ubuntu-toolchain-r-test]
          packages: [valgrind, g++-8, g++-8-multilib]
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CC=gcc-8 && CXX=g++-8 && CXXFLAGS=-m64"

    - name: "OSX Clang [XCode 9.4] [32-bit] [DBG]"
      os: osx
      osx_image: xcode9.4
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CXXFLAGS=-m32"

    - name: "OSX Clang [XCode 9.4] [64-bit] [DBG]"
      os: osx
      osx_image: xcode9.4
      env: BUILD_MATRIX="BUILD_TYPE=Debug && CXXFLAGS=-m64"

    - name: "OSX Clang [XCode 9.4] [32-bit] [REL]"
      os: osx
      osx_image: xcode9.4
      env: BUILD_MATRIX="BUILD_TYPE=Release && CXXFLAGS=-m32"

    - name: "OSX Clang [XCode 9.4] [64-bit] [REL]"
      os: osx
      osx_image: xcode9.4
      env: BUILD_MATRIX="BUILD_TYPE=Release && CXXFLAGS=-m64"

    - name: "Windows [MSVC] [64-bit]"
      os: windows
      env: BUILD_MATRIX="BUILD_TYPE=Debug" BUILD_TOOLCHAIN="Visual Studio 15 2017 Win64"

    - name: "Windows [MSVC] [64-bit]"
      os: windows
      env: BUILD_MATRIX="BUILD_TYPE=Release" BUILD_TOOLCHAIN="Visual Studio 15 2017 Win64"

before_install:
  - eval "$BUILD_MATRIX"

before_script:
  - mkdir build
  - cd build
  - cmake .. -G"${BUILD_TOOLCHAIN}" -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" -DASMJIT_BUILD_TEST=1
  - cd ..

script:
  - cd build
  - |
    if [[ "${TRAVIS_OS_NAME}" == "windows" ]]; then
      cmake --build . --config ${BUILD_TYPE} -- -nologo -v:quiet
      cd ${BUILD_TYPE}
    else
      make
    fi

  - ./asmjit_test_unit
  - ./asmjit_test_opcode > /dev/null
  - ./asmjit_test_x86_asm
  - ./asmjit_test_x86_cc
  - ./asmjit_test_x86_sections

after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then valgrind --leak-check=full --show-reachable=yes ./asmjit_test_unit; fi;
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then valgrind --leak-check=full --show-reachable=yes ./asmjit_test_x86_asm; fi;
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then valgrind --leak-check=full --show-reachable=yes ./asmjit_test_x86_cc; fi;
